# Generated by Django 5.2.15 on 2026-06-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=100)),
                ('compatible_cars', models.CharField(help_text='e.g., Swift, i20, Scorpio', max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('condition', models.CharField(choices=[('NEW', 'New Part'), ('USED', 'Used Part')], default='NEW', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='parts/')),
                ('description', models.TextField()),
            ],
        ),
    ]
