# Generated by Django 5.2.15 on 2026-06-27 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_bazaar', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlisting',
            name='car_image',
            field=models.ImageField(blank=True, null=True, upload_to='car_bazaar_pics/'),
        ),
        migrations.AddField(
            model_name='carlisting',
            name='has_noc',
            field=models.BooleanField(default=False, verbose_name='NOC Available'),
        ),
        migrations.AddField(
            model_name='carlisting',
            name='has_rc_card',
            field=models.BooleanField(default=False, verbose_name='RC Card Available'),
        ),
        migrations.AddField(
            model_name='carlisting',
            name='insurance_status',
            field=models.CharField(default='Expired', help_text='e.g. Comprehensive, Third Party, Expired', max_length=50),
        ),
        migrations.AddField(
            model_name='carlisting',
            name='seller_name',
            field=models.CharField(default='Unknown Seller', max_length=100),
        ),
        migrations.AddField(
            model_name='carlisting',
            name='seller_phone',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='carlisting',
            name='brand',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='carlisting',
            name='car_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='carlisting',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.district'),
        ),
    ]
