# Generated by Django 5.2.15 on 2026-06-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_bazaar', '0002_carlisting_car_image_carlisting_has_noc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carlisting',
            old_name='car_image',
            new_name='image_back',
        ),
        migrations.AddField(
            model_name='carlisting',
            name='image_dashboard',
            field=models.ImageField(blank=True, null=True, upload_to='car_bazaar_pics/'),
        ),
        migrations.AddField(
            model_name='carlisting',
            name='image_front',
            field=models.ImageField(blank=True, null=True, upload_to='car_bazaar_pics/'),
        ),
        migrations.AddField(
            model_name='carlisting',
            name='image_interior',
            field=models.ImageField(blank=True, null=True, upload_to='car_bazaar_pics/'),
        ),
        migrations.AlterField(
            model_name='carlisting',
            name='has_noc',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='carlisting',
            name='has_rc_card',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='carlisting',
            name='insurance_status',
            field=models.CharField(default='Expired', max_length=100),
        ),
    ]
